language: go
sudo: required
services:
  - docker

env:
  global:
    - APP_NAME=shell2telegram
    - DOCKER_USERNAME=msoap
    - secure: oAmnzBea5IZnhvCZ4PRQI0bf+F5eI7qWEdFPq7RT3PXACyvE6+IwQEXujU1JKgtc2J3oXKycFogAQgg89od8GVTYd2vAbbxgeqTfa3rd9crQ+D3BT2AjPOFgcqB+TnryJEBZ1G5XC9OmaUVEVL13VPwqD6oJ3mlshIlp+fznTVxN+eUuMo/HZmhqDTTlAywvg9i+CIxXwHjPy/pjDSIo+FRuHPVbhluL3Pihe3xKYtTjYditnnoC9EbTpdbgi6ijx4P0SjUNrU4nG6blBUo/eHRrLKofh9FFzpTqr+Cfe5WpfPQSZ6OTw1O++903EiwuUyu5teaYvqR6nOPP6mzVsbU4yh3WLlXQO1u46KUMo+TlAk9BM0QyP2to544npbue2ju+Hl/UyUEM7h8gqXGpfPOeQNJhcm38sv2YfBVM1aQcH9INDjLPRv5+ZCoKuU6MwH8q8ArRdTKWwNWnED48jant0gWyDou8SkvhNfY/ML7gONWDbwcB4plVK/f45vKJ4FWAyxk+Td//rUFH8JXlgWdm8TDxclxAPyc2JMlY7uOEVVRLqAJw2DRY94aAqU7c3ct29EFO8cULUhz4c3fCsiepkL8Hh8e5JR+j3V1N9imndccdwE+0fTLsx2HByuWM/PRcjW1aeZ66KNnACS1etRx09JCjhZAFV0kMacYBMzk=

matrix:
  fast_finish: true
  include:
    - go: 1.12.x
    - go: 1.x
      env: IS_LATEST_GO=true
    - go: master
  allow_failures:
    - go: master

before_install:
  - go get github.com/mattn/goveralls
  - go get github.com/kisielk/errcheck

install: go get -t ./...

script:
  - go test -race -v ./...
  - go vet ./...
  - errcheck ./...
  - diff <(gofmt -d .) <(echo -n "")
  - if [[ "$IS_LATEST_GO" == "true" ]] && [[ "$TRAVIS_BRANCH" == "master" ]] && [[ "$TRAVIS_EVENT_TYPE" == "push" ]]; then
      go test -covermode=count -coverprofile=profile.cov ./... && goveralls -coverprofile=profile.cov -service=travis-ci || true;
    fi

after_success:
  - if [[ "$IS_LATEST_GO" == "true" ]] && [[ $TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG ]] && [[ $TRAVIS_EVENT_TYPE == "push" ]]; then
      docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
      docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io &&
      docker build -t $DOCKER_USERNAME/$APP_NAME:latest . &&
      docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:latest &&
      docker push $DOCKER_USERNAME/$APP_NAME:latest &&
      docker push quay.io/$DOCKER_USERNAME/$APP_NAME:latest;
      if [[ -n $TRAVIS_TAG ]]; then
        docker tag $DOCKER_USERNAME/$APP_NAME:latest $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker tag $DOCKER_USERNAME/$APP_NAME:latest quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push $DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG &&
        docker push quay.io/$DOCKER_USERNAME/$APP_NAME:$TRAVIS_TAG;
      fi;
    fi

before_deploy:
  - curl -sSL https://raw.githubusercontent.com/msoap/etc/master/golang-cross-build/golang-cross-build.sh > $GOPATH/bin/golang-cross-build.sh
  - chmod 700 $GOPATH/bin/golang-cross-build.sh
  - gem install --no-ri --no-rdoc fpm
  - golang-cross-build.sh $APP_NAME
  - ls -l *.zip *.tar.gz *.deb

deploy:
  provider: releases
  api_key:
    secure: HP4lWsw8rLlRAkn0IA1+P4kF51m46f4n0h40juyIs6eJc/lrvu2jlHZxUxt2mlFU2f69vO/ycrfZB7z3A9ULX6Q0g9AFXy9/WbYEbIFj7CxBzcbpoIIN5uTNkUksrcsqLHGRbAbd4o2bstdYfxA/n6I1lO3Rn0sV1oT0BNE27raaLX2AUBVCuVW1AYyCsHKeaOHFjytp1aChk5yQ2xNmBYn4a+yfm37yGNZhG1FiNvpcma4CgZtB3cxO8+q31pwc5M77efIftGfQVmSPvS+r+m45iXlM9UuPaKDzomq2rKEGtQjlRYjy/17ghkElfAmHE8wZGZIa1qK/kRW8EKbl2AlIR3GY5egIQmr36acuB7hDoDJyEZW/q4i0DX+6Kcvx5zO4BLmzkyKSbtvzTLTGkNYcDBDQKHEnxTpkOG0Eted5mn2DeEHgJzIpcj2GsX8JLsChbyswW6bv24blRtphxrpGrZ5HtnVNxKJ9NLDYzYVdadFH+X4+dPxmBNKI6Ust/p0mCsuYaYKQLaMeuqsxI233hC2Riu01tAJcSCoh/8PnKJIZdNL8z7c0h2j60yH3KXnjenknD8Z5lZk6hX5arZ0czZermfnSffj3U/4Ubp8gL3oMwsU+mXTpH/oQXQSqci9Y+SbfgjeBNfjDOenQqbtX4BjMFotO3R3F3LwE9Xg=
  file_glob: "true"
  file:
    - "*.zip"
    - "*.tar.gz"
    - "*.deb"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    condition: $IS_LATEST_GO = true
    repo: msoap/$APP_NAME
